version: '3.4'

services:
  product-catalog-api:
    image: productcatalogapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=productcatalog;Username=postgres;Password=yourpassword
    command: >
      /bin/sh -c "dotnet ef database update && dotnet ProductCatalogApi.dll"

  db:
    image: postgres
    environment:
      POSTGRES_DB: productcatalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
